spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_jpa?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&failOverReadOnly=false&autoReconnect=true&useSSL=false
    username: root
    password: 123456  #配置数据源
server:
  port: 8090
database0:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test_jpa?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&failOverReadOnly=false&autoReconnect=true&useSSL=false
  username: root
  password: 123456  #配置数据源
  databaseName: test_jpa

database1:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/dbsharding?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&failOverReadOnly=false&autoReconnect=true&useSSL=false
  username: root
  password: 123456
  databaseName: dbsharding