server:
  port: 8084
spring:
  application:
    name: provider4
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8798/eureka/
  instance:
    instance_id: ${spring.cloud.client.hostname}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
