server:
  port: 8084
spring:
  application:
    name: provider4
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_jpa?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&failOverReadOnly=false&autoReconnect=true&useSSL=false
    username: root
    password: 123456  #配置数据源
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8798/eureka/
  instance:
    instance_id: ${spring.cloud.client.hostname}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
